[build]
  publish = "public"
  command = "hugo --gc --minify --buildFuture"

  [build.environment]
    HUGO_VERSION = "0.142.0"

[context.production.environment]
  HUGO_ENV           = "production"
  HUGO_ENABLEGITINFO = "true"

[context.split1]
  command = "hugo --gc --minify --enableGitInfo"

  [context.split1.environment]
    HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
  HUGO_VERSION = "0.142.0"


[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/admin/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
