import type { Models } from "appwrite";

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types -l ts ../svelte-app/src/lib/types`.

export enum MainStatus {
  ARCHIVE = "archive",
  LOCKED = "locked",
  PROPOSITION = "proposition",
  CONFIRMED = "confirmed",
  CANCELED = "canceled",
}

export enum RecettesTypeR {
  ENTREE = "entree",
  PLAT = "plat",
  DESSERT = "dessert",
  AUTRE = "autre",
}

export enum RecettesStatus {
  PUBLIC = "public",
  PRIVATE = "private",
  DELETED = "deleted",
}

export enum MaterielType {
  ELECTRONIC = "electronic",
  MANUAL = "manual",
  OTHER = "other",
  TOOLS = "tools",
  DISH = "dish",
  GAZ = "gaz",
  COOKING = "cooking",
  HYGIENE = "hygiene",
}

export enum MaterielStatus {
  OK = "ok",
  LOST = "lost",
  TOREPAIR = "torepair",
}

export enum EventTodoPriority {
  LOW = "low",
  MEDIUM = "medium",
  HIGH = "high",
}

export enum EventTodoStatus {
  TODO = "todo",
  DONE = "done",
  WAITING = "waiting",
  CANCELED = "canceled",
  INPROGRESS = "inprogress",
}

export enum EventTodoTaskOn {
  BEFORE_EVENT = "beforeEvent",
  ON_EVENT = "onEvent",
  AFTER_EVENT = "afterEvent",
}

export enum MaterielLoanStatus {
  ASKED = "asked",
  ACCEPTED = "accepted",
  REFUSED = "refused",
  CANCELED = "canceled",
  RETURNED = "returned",
  COMPLETED = "completed",
  ARCHIVED = "archived",
}

export type Main = Models.Row & {
  name: string;
  createdBy: string;
  isActive: boolean;
  originalDataHash: string | null;
  dateStart: string | null;
  dateEnd: string | null;
  teams: string[] | null;
  status: MainStatus | null;
  error: string | null;
  allDates: string[] | null;
  contributors: string[] | null;
  meals: string[] | null;
  description: string | null;
  minContrib: number;
  todos: string[] | null;
  teamsId: string[] | null;
  shareLinks: string[] | null;
};

export type Products = Models.Row & {
  ingredientRef: string | null;
  productName: string;
  stockReel: string | null;
  status: string;
  who: string[] | null;
  store: string;
  previousNames: string[] | null;
  isMerged: boolean;
  mergedFrom: string[] | null;
  mergeDate: string | null;
  mergeReason: string | null;
  isSynced: boolean;
  mergedInto: string | null;
  totalNeededOverride: string | null;
  updatedBy: string | null;
  productType: string | null;
  specs: string | null;
  mainId: string;
};

export type Purchases = Models.Row & {
  unit: string;
  store: string | null;
  status: string | null;
  notes: string;
  price: number | null;
  quantity: number;
  who: string | null;
  createdBy: string | null;
  orderDate: string | null;
  deliveryDate: string | null;
  invoiceId: string | null;
  invoiceTotal: number | null;
  products: string[] | null;
  mainId: string;
};

export type Recettes = Models.Row & {
  title: string;
  plate: number;
  preparation: string;
  draft: boolean;
  typeR: RecettesTypeR;
  categories: string[] | null;
  regime: string[] | null;
  publishedAt: string | null;
  createdBy: string;
  teams: string[] | null;
  materiel: string[] | null;
  prepAlt: string[] | null;
  ingredients: string[] | null;
  description: string | null;
  region: string | null;
  cuisson: boolean;
  quantite_desc: string | null;
  check: boolean;
  preparation24h: string | null;
  permissionWrite: string[] | null;
  serveHot: boolean;
  lockedBy: string | null;
  saison: string[] | null;
  auteur: string | null;
  astuces: string[] | null;
  status: RecettesStatus;
  rootRecipeId: string | null;
  versionLabel: string | null;
};

export type Kteams = Models.Row & {
  name: string;
  description: string | null;
  members: string[];
  invited: string[] | null;
  department: string | null;
  isPublic: boolean;
};

export type Materiel = Models.Row & {
  description: string | null;
  type: MaterielType;
  quantity: number;
  name: string;
  location: string | null;
  shareableWith: string[] | null;
  status: MaterielStatus;
  owner: string;
  storeIn: string[] | null;
  isStorage: boolean;
  deleted: boolean;
};

export type Locks = Models.Row & {
  userId: string;
  userName: string;
  expiresAt: string;
};

export type UserNotifications = Models.Row & {
  scope: string | null;
  notifications: string | null;
};

export type EventTodo = Models.Row & {
  eventId: string;
  taskName: string;
  taskDescription: string | null;
  dueDate: string | null;
  priority: EventTodoPriority | null;
  status: EventTodoStatus | null;
  taskOn: EventTodoTaskOn | null;
  requiredPeopleNb: number;
  locked: boolean;
  assignedTo: string[] | null;
};

export type MaterielLoan = Models.Row & {
  startDate: string;
  endDate: string;
  responsibleId: string | null;
  responsibleName: string | null;
  ownerId: string;
  ownerName: string | null;
  materiels: string[] | null;
  notes: string | null;
  status: MaterielLoanStatus;
  completedAt: string | null;
  returnedAt: string | null;
  returnNotes: string | null;
  eventName: string | null;
  eventId: string | null;
};

export type Teamdocs = Models.Row & {
  title: string;
  content: string | null;
  tags: string[] | null;
  isPublic: boolean;
  teamName: string | null;
  teamId: string | null;
  status: string;
  createdBy: string | null;
  lockedBy: string | null;
  lockedByName: string | null;
  eventId: string | null;
};

export type ShareLinks = Models.Row & {
  link_type: string;
  target_id: string;
  access_level: string;
  createdBy: string;
  expiresAt: string | null;
  maxUses: number | null;
  useCount: number;
  isActive: boolean;
};

export type InscriptionCampaigns = Models.Row & {
  campaign_id: string;
  team_id: string;
  max_inscriptions: number;
  current_count: number;
  expires_at: string | null;
  is_active: boolean;
};

export type EventMateriel = Models.Row & {
  eventId: string | null;
  name: string | null;
  quantity: number | null;
  type: string;
  who: string | null;
  where: string | null;
  sourceMaterielId: string | null;
  loanId: string | null;
  status: string;
  groupId: string | null;
  notes: string | null;
  createdBy: string | null;
  fromTeamName: string | null;
};
